import type { Metadata } from "next";
import "./globals.css";
import "./layout.css";
import NavigatorPages from "./Components/NavigatorPages";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="MainContainer">
          <div className="TitleContainer">
            <h1>Personajes Rick and Morty</h1>
          </div>
          <NavigatorPages/>
          {children}
        </div>
      </body>
    </html>
  );
}
